# apiVersion: v1
# kind: Pod
# metadata:
#   name: simple-nginx-pod
# spec:
#   containers:
#     - name: nginx
#       image: nginx:1.14.2
#       ports:
#         - containerPort: 80
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: storage-volume
# spec:
#   # initContainers:
#   #   - name: init-image
#   #     image: rkalluru/learnk8s:init-container-html-generator
#   #     volumeMounts:
#   #       - name: empty
#   #         mountPath: /mnt/html
#   containers:
#     - name: side-car-container
#       image: rkalluru/learnk8s:side-car-html-generator
#       volumeMounts:
#         - name: empty
#           mountPath: /mnt/html
#     - name: nginx
#       image: nginx:1.14.2
#       volumeMounts:
#         - name: empty
#           mountPath: /usr/share/nginx/html
#   volumes:
#     - name: empty
#       emptyDir: {}

# apiVersion: apps/v1
# kind: ReplicaSet
# metadata:
#   name: replicaset-example
#   labels:
#     app: nginx
#     project: example
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#         - name: nginx
#           image: nginx

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map1
data:
  player-lives: "3"
  ui_filename: "user-interface"
---
apiVersion: v1
kind: Pod
metadata:
  name: configMapPod
spec:
  containers:
    - name: config-container
      image: nginx:1.14.2
      env:
        - name: player-lives
          valueFrom:
            configMapRef:
              name: config-map1
              key: player-lives
        - name: ui_filename
          valueFrom:
            configMapRef:
              name: config-map1
              key: ui_filename
