apiVersion: v1
kind: Pod
metadata:
  name: simple-nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: storage volume
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      volumeMounts:
        - name: volume1
          mountPath: /usr/share/nginx/html
  volumes:
    - name: emptyDir
      emptyDir: {}
