apiVersion: v1
kind: Pod
metadata:
  name: simple-nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: storage-volume
spec:
  # initContainers:
  #   - name: init-image
  #     image: rkalluru/learnk8s:init-container-html-generator
  #     volumeMounts:
  #       - name: empty
  #         mountPath: /mnt/html
  containers:
    - name: side-car-container
      image: rkalluru/learnk8s:side-car-html-generator
      volumeMounts:
        - name: empty
          mountPath: /mnt/html
    - name: nginx
      image: nginx:1.14.2
      volumeMounts:
        - name: empty
          mountPath: /usr/share/nginx/html
  volumes:
    - name: empty
      emptyDir: {}
