name : Apply
on: 
  workflow_dispatch:
jobs:
  apply:
    runs-on: [self-hosted, linux, x64]
    env:
      vault_token: ${{ secrets.vault_token }}
    steps:
      - uses: actions/checkout@v4
      - name: terraform apply
        run: make dev-apply
    