name : Apply
on: 
  workflow_dispatch:
jobs:
  apply:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - name: terraform apply
        run: make dev-apply
    env:
    VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}