name : Tools Destroy
on: 
  workflow_dispatch:
jobs:
  toolsDestroy:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - name: terraform apply
        run: make tools-destroy
