name : Tools Apply 
on: 
  workflow_dispatch:
jobs:
  toolsApply:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - name: tools apply
        run: make tools-infra